const awarenessWalkData = [
    "Werde dir heute des Riechens und Schmeckens bewusst! Erkunde den Geruch und (wenn möglich auch) Geschmack der Dinge, die dir begegnen...",
    "Richte heute deine Aufmerksamkeit auf die Geräusche und Klänge des Tages! Lausche immer wieder in die Nähe und in die Ferne...",
    "Betrachte und genieße heute die Farben und Formen der Welt. Schau alles an und erlaube dir zu staunen...",
    "Fühle und spüre heute in die Begegnungen deines Körpers mit der Welt! Fühle Luft, Temperatur, Beschaffenheit, Strukturen...",
    "Spiele heute mit der Geschwindigkeit deiner Bewegung! Erkunde Langsamkeit und Tempo und sei immer genau so langsam, wie es braucht um den Moment ganz zu genießen...",
    "Übe dich heute darin, dich lautlos zu bewegen und halte auch Ausschau nach Verstecken und toten Winkeln, in denen du dich verbergen könnntest...",
    "Spiele heute mit deinem Körperradar als Wegweiser! Erlaube dir, deinen Weg nicht zu planen und stattdessen spüre von Moment zu Moment, wohin dein Körper sich bewegen möchte...",
    "Werde dir heute besonders der Welt der Pflanzen bewusst! Erkunde sie mit (wenn möglich) mit allen Sinnen...",
    "Werde dir heute besonders der Welt der Bäume bewusst!",
    "Werde dir heute besonders der Insekten und aller Kleintiere bewusst!",
    "Werde dir heute besonder der Vögel bewusst! Versuche dich in sie hineinzuversetzen und sie zu spüren, während du sie beobachtest...",
    "Werde dir heute besonders der Menschen bewusst! Achte auf ihre Erscheinung, auf ihr Verhalten und versuche sie zu erspüren...",
    "Achte heute immer mal wieder auf die Himmelsrichtungen! Frage dich: Wo ist Norden, wo Süden, Osten und Westen?",
    "Schaue heute nach (und sammle) Zunder- und Feuermaterialien!",
    "Schaue heute nach Orten für ein Lager! Wo findest könntest du Schutz finden vor den Elementen?",
    "Schaue heute nach Wasser! Wo findest du Wasser, dass du aufbereitet oder unaufbereitet trinken könntest?",
    "Schaue heute nach Nahrung! Wo findest du Pflanzen oder anderes Essbares in deiner Umgebung?",
    "Schaue heute nach möglichen Verstecken, in denen du dich verbergen könntest!",
    "Achte heute besonders auf alle Pfade, Wege und Lager von Tieren!",
    "Stelle dir heute Fragen zu den Dingen, die du beobachtest und versuche sie mit dem Verstand zu beantworten...",
    "Stelle dir heute Fragen zu den Dingen, die du beobachtest und warte auf eine Antwort aus deinem Inneren oder aus deiner Umgebung...",
];
